"use client";
import { useEffect, useState } from "react";
import { BookOpen, Building2, CalendarDays, Users } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { usePortal } from "@/components/portal-context";
import type { DashboardSummary, Metric } from "@/lib/contracts";
import { portalApi } from "@/lib/portal-api";
const cards = [{ key: "academicYears", label: "Academic years", icon: CalendarDays }, { key: "classes", label: "Classes", icon: Building2 }, { key: "subjects", label: "Subjects", icon: BookOpen }, { key: "students", label: "Students", icon: Users }];
function MetricCard({ label, metric, icon: Icon }: { label: string; metric?: Metric; icon: typeof Users }) { if (!metric) return <Card className="p-5"><Skeleton className="h-5 w-24" /><Skeleton className="mt-5 h-9 w-16" /></Card>; if (metric.availability === "unavailable") return <Card className="p-5"><div className="flex items-center justify-between"><p className="font-medium text-slate-700">{label}</p><Icon className="size-5 text-slate-400" /></div><p className="mt-5 text-sm font-medium text-slate-500">Unavailable</p><p className="mt-1 text-xs text-slate-400">{metric.unavailableReason}</p></Card>; return <Card className="p-5"><div className="flex items-center justify-between"><p className="font-medium text-slate-700">{label}</p><Icon className="size-5 text-orange-500" /></div><p className="mt-5 text-3xl font-bold text-slate-950">{metric.value}</p><p className="mt-1 text-xs text-slate-500">Current institution</p></Card>; }
export default function DashboardPage() { const { profile } = usePortal(); const [summary, setSummary] = useState<DashboardSummary | null>(null); const [error, setError] = useState(false); useEffect(() => { portalApi.dashboard().then(setSummary).catch(() => setError(true)); }, []); return <div className="mx-auto max-w-7xl"><div className="mb-6"><p className="text-sm font-medium text-orange-600">Overview</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Good day, {profile?.institution.name}</h1><p className="mt-2 text-slate-600">A secure snapshot of your academic setup.</p></div>{error ? <Card className="p-6"><h2 className="font-semibold text-slate-950">Dashboard unavailable</h2><p className="mt-2 text-sm text-slate-600">We could not load the dashboard right now. Please try again later.</p></Card> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ key, ...card }) => <MetricCard key={key} {...card} metric={summary?.metrics[key]} />)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="text-lg font-bold text-slate-950">Academic configuration</h2><p className="mt-1 text-sm text-slate-600">Available data for {summary?.institution.name ?? "your institution"}.</p><dl className="mt-5 grid grid-cols-2 gap-4">{["departments", "sections", "groups", "teacherAssignments"].map((key) => <div key={key} className="rounded-lg bg-slate-50 p-4"><dt className="text-xs font-medium capitalize text-slate-500">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="mt-1 text-xl font-bold text-slate-950">{summary?.metrics[key]?.availability === "available" ? summary.metrics[key].value : "—"}</dd></div>)}</dl></Card><Card className="p-6"><h2 className="text-lg font-bold text-slate-950">Operational modules</h2><p className="mt-1 text-sm text-slate-600">Future modules appear only when their trusted data source is delivered.</p><div className="mt-5 space-y-3">{["attendance", "collections", "dues", "admissions", "examinations"].map((key) => <div key={key} className="flex items-center justify-between rounded-lg border border-dashed border-slate-200 p-3"><span className="capitalize text-slate-700">{key}</span><span className="text-xs font-semibold text-slate-400">Unavailable</span></div>)}</div></Card></div></>}</div>; }
