"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Bell, ChevronDown, GraduationCap, LayoutDashboard, Menu, Search, Settings, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { usePortal } from "@/components/portal-context";
import { portalApi } from "@/lib/portal-api";
import { cn } from "@/lib/utils";
type NavItem = { label: string; capability: string; href?: string; icon: typeof LayoutDashboard; unavailable?: boolean };
const navigation: { label: string; items: NavItem[] }[] = [{ label: "Workspace", items: [{ label: "Dashboard", capability: "academic.read", href: "/dashboard", icon: LayoutDashboard }] }, { label: "Academic", items: [{ label: "Academic setup", capability: "academic.read", icon: GraduationCap, unavailable: true }] }, { label: "Administration", items: [{ label: "Roles & permissions", capability: "roles.manage", icon: Settings, unavailable: true }] }];
function Navigation({ onNavigate, collapsed = false }: { onNavigate?: () => void; collapsed?: boolean }) { const { profile } = usePortal(); const pathname = usePathname(); const [open, setOpen] = useState<Record<string, boolean>>({ Workspace: true, Academic: true, Administration: true }); const permissions = new Set(profile?.permissions ?? []); return <nav aria-label="Primary navigation" className="space-y-5 p-3">{navigation.map((group) => { const items = group.items.filter((item) => permissions.has(item.capability)); if (!items.length) return null; return <section key={group.label}><button type="button" onClick={() => setOpen((current) => ({ ...current, [group.label]: !current[group.label] }))} aria-expanded={open[group.label]} className={cn("flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-xs font-bold uppercase tracking-wider text-slate-500 hover:bg-slate-100", collapsed && "justify-center px-2")}><ChevronDown className={cn("size-4 transition-transform", !open[group.label] && "-rotate-90")} aria-hidden="true" /><span className={collapsed ? "sr-only" : ""}>{group.label}</span></button>{open[group.label] && <div className="mt-1 space-y-1">{items.map((item) => { const Icon = item.icon; const content = <><Icon className="size-5" aria-hidden="true" /><span className={collapsed ? "sr-only" : ""}>{item.label}</span>{item.unavailable && !collapsed && <span className="ml-auto text-[10px] font-semibold uppercase text-slate-400">Soon</span>}</>; return item.href ? <Link key={item.label} href={item.href} onClick={onNavigate} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium", pathname === item.href ? "bg-orange-50 text-orange-700" : "text-slate-700 hover:bg-slate-100", collapsed && "justify-center px-2")} aria-current={pathname === item.href ? "page" : undefined}>{content}</Link> : <div key={item.label} aria-disabled="true" className={cn("flex cursor-not-allowed items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-400", collapsed && "justify-center px-2")}>{content}</div>; })}</div>}</section>; })}</nav>; }
export function PortalShell({ children }: { children: React.ReactNode }) { const { profile, loading } = usePortal(); const router = useRouter(); const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); async function signOut() { await portalApi.logout(); router.replace("/login"); } if (loading || !profile) return <div className="grid min-h-screen place-items-center text-slate-600">Loading your portal…</div>; return <div className="min-h-screen bg-slate-100"><aside className={cn("fixed inset-y-0 left-0 hidden border-r border-slate-200 bg-white lg:block", collapsed ? "w-20" : "w-72")}><div className="flex h-16 items-center justify-between border-b px-4"><span className={cn("font-bold text-slate-950", collapsed && "sr-only")}>Edu Soft</span><Button variant="ghost" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle sidebar"><Menu className="size-5" /></Button></div><Navigation collapsed={collapsed} /></aside><header className={cn("sticky top-0 z-20 flex h-16 items-center gap-3 border-b border-slate-200 bg-white px-4", collapsed ? "lg:ml-20" : "lg:ml-72")}><Sheet open={mobileOpen} onOpenChange={setMobileOpen}><SheetTrigger asChild><Button variant="ghost" className="lg:hidden" aria-label="Open navigation"><Menu className="size-5" /></Button></SheetTrigger><SheetContent><div className="flex h-16 items-center justify-between border-b px-4"><strong>Edu Soft</strong><Button variant="ghost" aria-label="Close navigation" onClick={() => setMobileOpen(false)}><X className="size-5" /></Button></div><Navigation onNavigate={() => setMobileOpen(false)} /></SheetContent></Sheet><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-950">{profile.institution.name}</p><p className="text-xs text-slate-500">{profile.institution.timezone}</p></div><label className="relative hidden max-w-sm flex-1 md:block"><span className="sr-only">Search portal</span><Search className="absolute left-3 top-3 size-4 text-slate-400" aria-hidden="true" /><Input placeholder="Search (coming soon)" disabled className="pl-9" /></label><Button variant="ghost" aria-label="Notifications"><Bell className="size-5" /></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" aria-label="Open user menu">Account</Button></DropdownMenuTrigger><DropdownMenuContent className="z-50 mt-2 rounded-lg border bg-white p-1 shadow-lg"><DropdownMenuItem onSelect={signOut} className="cursor-pointer rounded px-3 py-2 text-sm outline-none hover:bg-slate-100">Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header><main className={cn("p-4 sm:p-6", collapsed ? "lg:ml-20" : "lg:ml-72")}>{children}</main></div>; }
